import React, { useState } from 'react';
import { Users, DollarSign, MapPin, Check, TrendingUp, Building, Globe, Briefcase, Target, Zap, ChevronRight, X, ExternalLink, Calendar, Layers, BarChart, Package, Info } from 'lucide-react';
import { AnalysisData, PotentialBuyer } from '../types';

interface StateAnalysisProps {
  data: AnalysisData;
  onApprove: () => void;
}

const BuyerDetailModal: React.FC<{ buyer: PotentialBuyer; onClose: () => void }> = ({ buyer, onClose }) => {
  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-fade-in">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-2xl transform transition-all">
        <div className="p-6 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center">
            <img src={buyer.avatarUrl} alt={buyer.name} className="w-16 h-16 rounded-full mr-4 border-2 border-slate-200" />
            <div>
              <h3 className="text-2xl font-bold text-slate-900">{buyer.name}</h3>
              <a href={buyer.website} target="_blank" rel="noopener noreferrer" className="text-sm text-blue-600 hover:underline flex items-center">{buyer.website} <ExternalLink className="w-4 h-4 ml-1.5" /></a>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-full hover:bg-slate-100 text-slate-500">
            <X className="w-6 h-6" />
          </button>
        </div>
        <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6 text-sm">
          <div className="flex items-start">
            <Calendar className="w-5 h-5 mr-3 mt-0.5 text-slate-500 flex-shrink-0" />
            <div><span className="font-semibold text-slate-800">Join Date:</span> <span className="text-slate-600">{buyer.joinDate}</span></div>
          </div>
          <div className="flex items-start">
            <Building className="w-5 h-5 mr-3 mt-0.5 text-slate-500 flex-shrink-0" />
            <div><span className="font-semibold text-slate-800">Industry:</span> <span className="text-slate-600">{buyer.industry}</span></div>
          </div>
          <div className="flex items-start">
            <Briefcase className="w-5 h-5 mr-3 mt-0.5 text-slate-500 flex-shrink-0" />
            <div><span className="font-semibold text-slate-800">Business Model:</span> <span className="text-slate-600">{buyer.businessModel}</span></div>
          </div>
          <div className="flex items-start">
            <BarChart className="w-5 h-5 mr-3 mt-0.5 text-slate-500 flex-shrink-0" />
            <div><span className="font-semibold text-slate-800">Historical Inquiries:</span> <span className="text-slate-600">{buyer.historicalInquiries}</span></div>
          </div>
          <div className="flex items-start col-span-1 md:col-span-2">
            <Package className="w-5 h-5 mr-3 mt-0.5 text-slate-500 flex-shrink-0" />
            <div><span className="font-semibold text-slate-800">Intended Products:</span> <span className="text-slate-600">{buyer.intendedProducts.join(', ')}</span></div>
          </div>
          <div className="flex items-start col-span-1 md:col-span-2">
            <MapPin className="w-5 h-5 mr-3 mt-0.5 text-slate-500 flex-shrink-0" />
            <div><span className="font-semibold text-slate-800">Location:</span> <span className="text-slate-600">{buyer.location}</span></div>
          </div>
        </div>
        <div className="p-6 bg-slate-50 border-t border-slate-200 rounded-b-2xl">
            <p className="text-sm text-slate-600 flex items-center"><Info className="w-4 h-4 mr-2 text-blue-500"/>Buyer information is sourced from our proprietary database, not generated by AI.</p>
        </div>
      </div>
    </div>
  );
};

export const StateAnalysis: React.FC<StateAnalysisProps> = ({ data, onApprove }) => {
  const [selectedBuyer, setSelectedBuyer] = useState<PotentialBuyer | null>(null);

  return (
    <div className="max-w-7xl mx-auto py-8 animate-fade-in">
       {selectedBuyer && <BuyerDetailModal buyer={selectedBuyer} onClose={() => setSelectedBuyer(null)} />}

      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-8 px-4 sm:px-0">
        <div>
          <h2 className="text-3xl font-bold text-slate-900">AI Market Analysis Report</h2>
          <p className="text-slate-500 mt-1">High-potential opportunities have been identified for your product.</p>
        </div>
        <div className="mt-4 sm:mt-0 px-4 py-2 bg-blue-50 text-blue-800 rounded-full text-sm font-semibold border border-blue-200 flex items-center">
          <TrendingUp className="w-4 h-4 mr-2" />
          Status: High-Confidence Analysis
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Column: Buyers & Competitors */}
        <div className="lg:col-span-2 space-y-8">

          {/* 1. Potential Buyers */}
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
            <div className="flex items-center mb-4">
              <div className="p-3 bg-green-100 rounded-full mr-4">
                <Users className="h-6 w-6 text-green-700" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-slate-800">Potential Buyers Directory</h3>
                <p className="text-slate-500">Total Identified Leads: <span className="font-bold text-green-700">{data.potentialBuyers.total}</span> (Sourced from our verified database)</p>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {data.potentialBuyers.top10.map((buyer) => (
                <button 
                  key={buyer.id} 
                  onClick={() => setSelectedBuyer(buyer)}
                  className="flex items-center text-left p-3 bg-slate-50 rounded-lg border border-slate-200 hover:bg-slate-100 hover:border-slate-300 transition-all focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  <img src={buyer.avatarUrl} alt={buyer.name} className="w-12 h-12 rounded-full mr-4"/>
                  <div className="flex-grow">
                    <p className="font-semibold text-slate-800">{buyer.name}</p>
                    <p className="text-xs text-slate-500">{buyer.industry} - {buyer.location}</p>
                  </div>
                  <ChevronRight className="h-5 w-5 text-slate-400" />
                </button>
              ))}
            </div>
          </div>

          {/* 3. Top Competitors */}
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
            <div className="flex items-center mb-4">
              <div className="p-3 bg-red-100 rounded-full mr-4">
                <Target className="h-6 w-6 text-red-700" />
              </div>
              <h3 className="text-xl font-bold text-slate-800">Top 5 Competitor Analysis</h3>
            </div>
            <div className="space-y-4">
              {data.topCompetitors.map((competitor, index) => (
                <div key={index} className="p-4 bg-slate-50 rounded-lg border border-slate-200">
                  <div className="flex items-center justify-between mb-2">
                    <p className="font-semibold text-slate-800 text-base">{competitor.name}</p>
                    <a href={`http://${competitor.website}`} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline text-sm font-medium">
                      {competitor.website}
                    </a>
                  </div>
                  <ul className="space-y-1.5 text-sm text-slate-600">
                    {competitor.advantages.map((advantage, advIndex) => (
                      <li key={advIndex} className="flex items-start">
                        <Zap className="w-4 h-4 mr-2 mt-0.5 text-yellow-500 flex-shrink-0" />
                        <span>{advantage}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

        </div>

        {/* Right Column: Niche Markets & Strategies */}
        <div className="space-y-8">

          {/* 2. Niche Markets */}
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
            <div className="flex items-center mb-4">
              <div className="p-3 bg-purple-100 rounded-full mr-4">
                <Briefcase className="h-6 w-6 text-purple-700" />
              </div>
              <h3 className="text-xl font-bold text-slate-800">Niche Market Volume</h3>
            </div>
            <div className="space-y-3">
              {data.nicheMarkets.map((market, index) => (
                <div key={index} className="flex justify-between items-center p-3 bg-slate-50 rounded-lg border border-slate-200">
                  <p className="font-semibold text-slate-700">{market.name}</p>
                  <p className="font-bold text-lg text-purple-700">{market.volume}</p>
                </div>
              ))}
            </div>
          </div>

          {/* 4. B2B Strategies */}
          <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
             <div className="flex items-center mb-4">
              <div className="p-3 bg-yellow-100 rounded-full mr-4">
                <Globe className="h-6 w-6 text-yellow-700" />
              </div>
              <h3 className="text-xl font-bold text-slate-800">Core B2B Strategies</h3>
            </div>
            <ul className="space-y-2.5 text-sm text-slate-700">
              {data.b2bStrategies.map((strategy, index) => (
                <li key={index} className="flex items-start">
                  <Check className="w-4 h-4 mr-2.5 mt-0.5 text-emerald-500 flex-shrink-0" />
                  <span>{strategy}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Action Bar */}
      <div className="fixed bottom-0 left-0 right-0 bg-white/80 backdrop-blur-sm border-t border-slate-200 p-4 shadow-lg md:static md:shadow-none md:bg-transparent md:border-0 md:p-0 md:mt-12">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between bg-slate-900 text-white p-2 rounded-xl md:pl-8">
          <div className="text-sm text-slate-300 mb-2 md:mb-0 text-center md:text-left">
            Ready to proceed? The next step is to generate a marketing strategy and launch the automated outreach campaign.
          </div>
          <button
            onClick={onApprove}
            className="w-full md:w-auto bg-emerald-500 hover:bg-emerald-600 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all flex items-center justify-center"
          >
            <Check className="w-5 h-5 mr-2" />
            Approve & Generate Outreach
          </button>
        </div>
      </div>
    </div>
  );
};